spring.application.name=CFS
server.port=8081

# JSP View Resolver Configuration
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/CFS?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Abhi#07
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Disable Security for now while refactoring to avoid 401s on static resources and API calls
spring.security.user.name=admin
spring.security.user.password=admin
